server:
  port: 8084

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/sg_payment_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true